#
# https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/99-clickhouseinstallation-max.yaml
#
---
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: chi-4782
  namespace: clickhouse
spec:
  #
  configuration:
    # 
    # WIP
    #
    users:
      # grafana/password:
      #   valueFrom:
      #     secretKeyRef:
      #       name: clickhouse-grafana
      #       key: grafana
      # grafana/networks/ip: "::/0"
      # grafana/networks/host_regexp: "disabled"
      # default/access_management: 1
      # default/networks/ip: "::/0"

    #
    zookeeper:
      nodes:
        - host: chk-chk-b593-chk-b593-0-0
          port: 2181
        - host: chk-chk-b593-chk-b593-0-1
          port: 2181
        - host: chk-chk-b593-chk-b593-0-2
          port: 2181
    #
    clusters:
      - name: ch-4782
        templates:
          podTemplate: clickhouse-4782
        layout:
          shardsCount: 1
          replicasCount: 1
        files:
          logger.xml: |
            <clickhouse>
              <yandex>
                <logger>
                  <level>information</level>
                  <console>1</console>
                </logger>
              </yandex>
            </clickhouse>
  #
  templates:
    podTemplates:
      - name: clickhouse-4782
        spec:
          containers:
            #
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:24.5
              volumeMounts:
                #
                - name: clickhouse-storage-4782
                  mountPath: /var/lib/clickhouse

    #
    # Manual action needed!
    # We use rook-ceph, change to you storage specific situation
    #
    volumeClaimTemplates:
      - name: clickhouse-storage-4782
        provisioner: StatefulSet
        reclaimPolicy: Retain
        spec:
          storageClassName: rook-ceph-block
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
