#
# https://github.com/nats-io/k8s/blob/main/helm/charts/nats/values.yaml
# https://github.com/nats-io/nats-box
#

config:
  cluster:
    enabled: true
    replicas: 3

  jetstream:
    enabled: true

    fileStore:
      enabled: true
      dir: /data

      pvc:
        enabled: true
        size: 10Gi
